services:
  remora_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: remora_backend
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data
    restart: always

  remora_web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: remora_web
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - remora_backend
    restart: always
